import { NextRequest, NextResponse } from 'next/server';
import { generateDomainVariationsViaMCP } from '@/lib/instantDomainMCP';

/**
 * Domain Generation API Route
 * 
 * Generates creative domain name variations using AI or algorithmic approaches.
 * This uses the Instant Domain Search MCP generate_domain_variations function.
 */

export async function POST(request: NextRequest) {
  try {
    const { keyword, count = 10 } = await request.json();

    if (!keyword || !keyword.trim()) {
      return NextResponse.json(
        { error: 'Keyword parameter is required' },
        { status: 400 }
      );
    }

    const cleanKeyword = keyword.toLowerCase().replace(/\s+/g, '');

    // Option 1: Use Instant Domain Search MCP (FREE - Recommended)
    try {
      const mcpResult = await generateDomainVariationsViaMCP({
        keyword: cleanKeyword,
        count,
      });
      
      // Parse MCP response
      const variations = parseMCPGenerateResults(mcpResult, cleanKeyword, count);
      return NextResponse.json(variations);
    } catch (mcpError) {
      console.warn('⚠️ MCP generation failed, trying fallback:', mcpError);
    }

    // Option 2: Use OpenAI/Gemini for AI-powered generation
    if (process.env.OPENAI_API_KEY || process.env.GEMINI_API_KEY) {
      return await generateWithAI(cleanKeyword, count);
    }

    // Option 3: Use algorithmic generation (free, fast)
    const variations = generateAlgorithmicVariations(cleanKeyword, count);
    return NextResponse.json(variations);

  } catch (error) {
    console.error('❌ Domain generation error:', error);
    return NextResponse.json(
      { error: 'Failed to generate domain variations' },
      { status: 500 }
    );
  }
}

// ============================================================================
// Helper Functions
// ============================================================================

function parseMCPGenerateResults(mcpResult: any, keyword: string, count: number) {
  try {
    if (Array.isArray(mcpResult)) {
      const textContent = mcpResult.find((item: any) => item.type === 'text');
      if (textContent && textContent.text) {
        try {
          const parsed = JSON.parse(textContent.text);
          if (Array.isArray(parsed)) {
            return parsed.map((item: any) => ({
              domain: item.domain || `${keyword}.com`,
              available: item.available !== false,
              score: item.score || 85,
              reason: item.reason || 'Generated by AI',
            }));
          }
        } catch (parseError) {
          // If not JSON, skip text response
        }
      }
    }
    
    return generateAlgorithmicVariations(keyword, count);
  } catch (error) {
    console.error('Error parsing MCP generate results:', error);
    return generateAlgorithmicVariations(keyword, count);
  }
}

// ============================================================================
// AI-Powered Generation
// ============================================================================

async function generateWithAI(keyword: string, count: number) {
  try {
    // Example with OpenAI
    if (process.env.OPENAI_API_KEY) {
      const response = await fetch('https://api.openai.com/v1/chat/completions', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${process.env.OPENAI_API_KEY}`,
        },
        body: JSON.stringify({
          model: 'gpt-4',
          messages: [
            {
              role: 'system',
              content: 'You are a creative domain name generator. Generate brandable, memorable domain names.',
            },
            {
              role: 'user',
              content: `Generate ${count} creative, brandable domain name variations for the keyword "${keyword}". Make them short, memorable, and pronounceable. Return as JSON array with fields: domain, score (0-100), reason.`,
            },
          ],
          temperature: 0.8,
        }),
      });

      if (response.ok) {
        const data = await response.json();
        const content = data.choices[0].message.content;
        const variations = JSON.parse(content);
        return NextResponse.json(variations);
      }
    }

    // Fallback to algorithmic
    return NextResponse.json(generateAlgorithmicVariations(keyword, count));
  } catch (error) {
    console.error('AI generation error:', error);
    return NextResponse.json(generateAlgorithmicVariations(keyword, count));
  }
}

// ============================================================================
// Algorithmic Generation (Free, Fast)
// ============================================================================

function generateAlgorithmicVariations(keyword: string, count: number) {
  const variations = [];
  
  // Prefixes that work well for domains
  const prefixes = [
    'get', 'my', 'the', 'try', 'use', 'go', 'hey', 'app',
    'join', 'meet', 'find', 'see', 'make', 'build', 'start'
  ];
  
  // Suffixes that work well for domains
  const suffixes = [
    'app', 'hub', 'pro', 'hq', 'lab', 'io', 'ai', 'tech',
    'now', 'live', 'zone', 'spot', 'base', 'kit', 'box'
  ];

  // Alternative TLDs
  const tlds = ['.com', '.ai', '.io', '.co', '.app', '.dev', '.tech'];

  // 1. Original with different TLDs
  variations.push({
    domain: `${keyword}.com`,
    available: true,
    score: 95,
    reason: 'Short, memorable, and brandable',
  });

  // 2. Prefix variations
  for (let i = 0; i < Math.min(3, count - 1); i++) {
    const prefix = prefixes[i];
    variations.push({
      domain: `${prefix}${keyword}.com`,
      available: true,
      score: 88 - i * 2,
      reason: `Action-oriented with "${prefix}" prefix`,
    });
  }

  // 3. Suffix variations
  for (let i = 0; i < Math.min(3, count - variations.length); i++) {
    const suffix = suffixes[i];
    variations.push({
      domain: `${keyword}${suffix}.com`,
      available: true,
      score: 90 - i * 2,
      reason: `Modern and tech-focused with "${suffix}"`,
    });
  }

  // 4. Alternative TLDs
  for (let i = 1; i < Math.min(tlds.length, count - variations.length + 1); i++) {
    variations.push({
      domain: `${keyword}${tlds[i]}`,
      available: true,
      score: 87 - i,
      reason: `Perfect for ${getTLDDescription(tlds[i])}`,
    });
  }

  // 5. Combined variations (prefix + suffix)
  if (variations.length < count) {
    for (let i = 0; i < Math.min(2, count - variations.length); i++) {
      const prefix = prefixes[i];
      const suffix = suffixes[i];
      variations.push({
        domain: `${prefix}${keyword}${suffix}.com`,
        available: true,
        score: 82 - i,
        reason: `Descriptive combination with "${prefix}" and "${suffix}"`,
      });
    }
  }

  // 6. Shortened versions (if keyword is long)
  if (keyword.length > 8 && variations.length < count) {
    const shortened = keyword.slice(0, 6);
    variations.push({
      domain: `${shortened}.com`,
      available: true,
      score: 80,
      reason: 'Shorter, easier to remember',
    });
  }

  // 7. Vowel variations (creative spellings)
  if (variations.length < count) {
    const vowelVariation = keyword.replace(/er$/, 'r').replace(/a/g, '');
    if (vowelVariation !== keyword && vowelVariation.length >= 4) {
      variations.push({
        domain: `${vowelVariation}.com`,
        available: true,
        score: 78,
        reason: 'Modern spelling variation',
      });
    }
  }

  return variations.slice(0, count);
}

function getTLDDescription(tld: string): string {
  const descriptions: Record<string, string> = {
    '.ai': 'AI and machine learning products',
    '.io': 'startups and tech companies',
    '.co': 'modern businesses and companies',
    '.app': 'applications and software',
    '.dev': 'developers and tech projects',
    '.tech': 'technology companies',
    '.online': 'online businesses',
    '.shop': 'e-commerce and retail',
  };
  return descriptions[tld] || 'your business';
}
