/**
 * Domain-related type definitions
 * @module types/domain
 */

/**
 * Represents a link to a domain registrar for purchasing a domain
 */
export interface RegistrarLink {
  /** Name of the registrar (e.g., "GoDaddy", "Namecheap") */
  name: string;
  /** URL to register the domain at this registrar */
  url: string;
  /** Optional price for registration */
  price?: string;
  /** Whether this is an affiliate link */
  affiliate: boolean;
}

/**
 * Result of a domain availability check
 */
export interface DomainCheckResult {
  /** The full domain name (e.g., "example.com") */
  domain: string;
  /** Whether the domain is available for registration */
  available: boolean;
  /** The top-level domain (e.g., "com", "io") */
  tld: string;
  /** Timestamp when the check was performed */
  checkedAt: Date;
  /** Optional list of registrar links for available domains */
  registrarLinks?: RegistrarLink[];
}

/**
 * A domain name suggestion generated by the system
 */
export interface DomainSuggestion {
  /** The suggested domain name */
  domain: string;
  /** Relevance/quality score (0-100) */
  score: number;
  /** Optional availability status if checked */
  available?: boolean;
  /** Source of the suggestion */
  source: 'keyword' | 'ai' | 'geo';
}
